### ISSUE TITLE
Prebuilt UI not responsive when displayed in a container (using containerId)

### ISSUE THREAD

**Issue by killianhuyghe** [videosdk-live/videosdk.live#1]
My goal is to embed the prebuilt UI in one of my (React) view so that it takes roughly half the screen (horizontally for large screen devices and vertically otherwise).

Some examples:
- The `join meeting` button sometimes gets close to or partially under the bottom edge of the container when using half of the height on tablet/small laptop form factors.
- The `join screen` view is not responsive for any small container (anything not full-size desktop), it is not compatible with mobile devices.

I know one workaround probably is to not use the prebuilt UI, but I'd like to get a first version out as fast as possible with as little work on the UI as possible.

**Comment by arjun-kava** [comment]
This is resolved in the latest version.
