### ISSUE TITLE
Camera and mic not accessible

### ISSUE THREAD

**Issue by adityaaktth** [videosdk-live/videosdk.live#2]
Camera and mic not accessible
![Screenshot_2022-03-06-20-05-35-65_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/100430141/156927824-ad211f3d-e4dc-4df2-b59f-10aa3341c59b.jpg)

**Comment by adityaaktth** [comment]
I not understand

**Comment by adityaaktth** [comment]
> Hey @adityaaktth which SDK are you using?

I not understand

**Comment by arjun-kava** [comment]
Hey, Are you using prebuilt SDK?

**Comment by adityaaktth** [comment]
Yes

**Comment by ahmedbhesaniya97** [comment]
Hey @adityaaktth,
Your website seems not secure, that's why mic and camera permission is not asked by browser.
Please make it secure and try again.
