### ISSUE TITLE
Duplicated participants when only one participant is joining

### ISSUE THREAD

**Issue by mohamedsamara** [videosdk-live/videosdk.live#4]
Hello, 

Not sure what the issue but participants in the below snippet returns duplicated participants. The issue does not appear in react/react-dom @17.0.2
```
  import { useMeeting } from "@videosdk.live/react-sdk";
  const { participants } = useMeeting();
```
Which React version this issue appear?
```
 "react": "^18.1.0"
 "react-dom": "^18.1.0"
```

[codesandbox]
https://codesandbox.io/s/great-ganguly-km6pke
[code repo]
https://github.com/mohamedsamara/react-videosdk-codesandbox

Thanks,
Mohamed

**Comment by rajansurani** [comment]
@mohamedsamara Please remove the Strictmode from index.tsx file and it should be resolved

**Comment by mohamedsamara** [comment]
Thank you @rajansurani! It works without StrictMode. I guess it is related to StrictMode causing double rendering to components.
