### ISSUE TITLE
Getting CORS Error on Login using Google

### ISSUE THREAD

**Issue by jakerb** [videosdk-live/videosdk.live#5]
Getting the following error when trying to login to app.videosdk.live using Google to authenticate. Completely unable to login to the dashboard.

`
Access to fetch at 'https://api.videosdk.live/v1/users/auth' from origin 'https://app.videosdk.live' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

**Comment by arjun-kava** [comment]
This is resolved.
