### ISSUE TITLE
left screen problem on light theme

### ISSUE THREAD

**Issue by admir4l** [videosdk-live/videosdk.live#6]
I am using @videosdk.live/rtc-js-prebuilt@0.3.23 and with the 'LIGHT' theme left screen text is unreadable!

![Screenshot_20221213_210811](https://user-images.githubusercontent.com/57384/207405886-7cf7d54c-98d5-4c4f-a54e-cd50410e45e2.png)

**Comment by arjun-kava** [comment]
Hey, @admir4l Thanks for raising this. We took it as a feedback and going to fix this in next version.

**Comment by admir4l** [comment]
Thanks @arjun-kava 
Is there any open-source and up-to-date version of the prebuild UI available to fork and use until the fix?
