### ISSUE TITLE
Quit Spamming

### ISSUE THREAD

**Issue by maxxfrazer** [videosdk-live/videosdk.live#8]
Hi, could I request you stop spamming other communities with messages directing people to your website?

Multiple customers have reported it to us and find it very annoying.

**Comment by arjun-kava** [comment]
Hey, @maxxfrazer 

Thanks a lot for raising this issue as of now. We are not aware of the spam account. Can you please let us know id of account so we can identify it? 

Thanks.

**Comment by maxxfrazer** [comment]
There are multiple accounts sending the same message in our public slack promoting your product hunt launch. We’ve had quite a few customers reaching out who don’t want to be spammed in this way.

You may want to be in contact with your marketing teams if they are responsible. Very poor behaviour.

![IMG_8090](https://user-images.githubusercontent.com/5754073/231108035-da3ec3bf-bdf6-4f3d-ab40-981b7bc03488.jpeg)

**Comment by arjun-kava** [comment]
Hey, @maxxfrazer 
Thanks for pointing this out. 

I am on behalf of the management of the company are not aware of such kind of scenario and if it would be by our marketing team, I will assure you that we will take this on priority and make sure that won't happen again.

I am extremely sorry for such kind of experience for you and your customers. It seems something not intended or intentionally done. 
Thanks.

**Comment by arjun-kava** [comment]
Sure, I will keep you posted.
Please give us some time to take this internally and get back to you. 
Thanks, have a great day.
