### ISSUE TITLE
 "TypeError: Cannot read properties of undefined (reading 'enumerateDevices')"

### ISSUE THREAD

**Issue by Stephen-Ch** [videosdk-live/videosdk.live#9]
We're using the WebRTC API to enable webcam access. The video API works locally, but when I deploy it to my host, I get the following error:

php
Copy code
TypeError: Cannot read properties of undefined (reading 'enumerateDevices')
    at e.<anonymous> (main.6e092ceb.js:2:190551)
    at l (main.6e092ceb.js:2:632180)
    at Generator._invoke (main.6e092ceb.js:2:631968)
    at Generator.next (main.6e092ceb.js:2:632609)
    at n (main.6e092ceb.js:2:651750)
    at s (main.6e092ceb.js:2:651953)
    at main.6e092ceb.js:2:652012
    at new Promise (<anonymous>)
    at e.<anonymous> (main.6e092ceb.js:2:651893)
    at e.<anonymous> (main.6e092ceb.js:2:191304)

I believe this error is related to the navigator.mediaDevices.enumerateDevices() method used to retrieve a list of available media input and output devices. However, I am not sure how to resolve this issue.

I have already checked the browser compatibility and ensured that the correct permissions are granted to access the user's webcam and microphone. I have also verified that the necessary libraries and dependencies are included and up-to-date in my project.

Can anyone provide any guidance on how to troubleshoot and fix this error?

**Comment by rajansurani** [comment]
@Stephen-Ch  Is your website running on `SSL, i.e. https` ?

**Comment by Stephen-Ch** [comment]
No, we'll try that. Thanks

**Comment by Stephen-Ch** [comment]
Worked great, thanks!
